#ifndef SPACEFIGHTERS_CONSTANTS_HPP
#define SPACEFIGHTERS_CONSTANTS_HPP

#define WINDOW_WIDTH 700
#define WINDOW_HEIGHT 900
#define WINDOW_BORDER_SIZE 5.f
#define SPLASH_SCREEN_TIME 3000
#define COLOR_TRANSPARENT sf::Color(255, 255, 255, 0)
#define COLOR_LIGHT_BLUE sf::Color(15, 168, 214)
#define COLOR_BLUE sf::Color(30, 39, 56)
#define COLOR_DARK_BLUE sf::Color(24, 31, 45)
#define COLOR_DARKER_BLUE sf::Color(4, 6, 12)
#define COLOR_RED sf::Color(165, 23, 23)
#define GAME_HEADER_HEIGHT 54.f
#define GAME_SOUND std::string("GAME_SOUND")
#define GAME_FONT "GAME_FONT"
#define SOUND_ON_TEXTURE "SOUND_ON"
#define SOUND_OFF_TEXTURE "SOUND_OFF"
#define BACKGROUND_TEXTURE "BACKGROUND"
#define ASTEROID_TEXTURE "ASTEROID"
#define SPACESHIP_TEXTURE "SPACESHIP"

#endif